### ISSUE TITLE
File uploading with Duplicate names

### ISSUE THREAD

**Issue by kasvith** [joomla-projects/media-manager-improvement#184]
### Steps to reproduce the issue
- Go to Media Manager
- Upload a file named **abc.jpg** to any folder (just an example)
- Pick another file, name it also as **abc.jpg**
- Try to upload to same folder

### Expected result
- Automatically renamed new file in the folder or if the content identical, an error message it already exists in the current folder

### Actual result
- Media Manager stays silent in duplicate name uploads

### System information (as much as possible)
PHP 7.1 Window 10

### Additional comments
- We need a mechanism for rename files like **abc - (1).jpg** or etc

**Comment by dneukirchen** [comment]
Thx for reporting. We had a discussion about this some days ago:

>David Neukirchen
So one question that popped up: how should we handle file upload requests, if the file already exists in the target directory?

> Dimitris Grammatiko
the old way was to refuse the upload
I suggest to create a filename-1.ext similar to articles with the same alias

>David Neukirchen
that would be possible... but maybe there are use-cases where the user wants to replace a file with an updated version of that file? I dont know...

> Dimitris Grammatiko shared a link
In the old controller and plugins I had introduced a way to allow overwriting: https://github.com/joomla-projects/media-manager-improvement/pull/19/files#diff-e5953bc3eadad37980d677840c9d4f6dR154

> Thomas Hunziker
We had that discussion in the past. Just refuse the upload or if you can ask if it should overwrite the file. Don't change the filename to something else, that would be very unexpected.

We decided to not override or rename the file automatically. We need to ask the user if he wants to override the file, otherwise he needs to change the filename.

**Comment by kasvith** [comment]
@dneukirchen I suggest to add an option which will automatically rename duplicate files or ignore them in options(should be in the Media Manager itself), so user can toggle it anytime, if we plan to do drag n drop uploads, user will be annoyed to each time look if file exists or rename files

**Comment by kasvith** [comment]
@dneukirchen if user want to update an file, we can do a simple and handy thing, we can create a context menu, where user can update the selected file

**Comment by dneukirchen** [comment]
Good ideas!

Config Options are kind of handicapped in the joomla world. Imo joomla has already too many of them. We need to be very careful and think twice, if we want to add another one. In this case i would say we should stick with a dialog/context modal like you suggested in you second comment.

So the workflow for already existing files could be:

* Ask the user if he wants to override it
     * yes => override the file (send an additional param to api)
     * no => show input field where the user can change the filename manually

**Comment by kasvith** [comment]
Can we upload multiple files ?

**Comment by dneukirchen** [comment]
yes, you can select multiple files for upload, but the upload will be done one by one...

**Comment by kasvith** [comment]
Yes, think of a situation user uploaded multiple and each of them have a similar name in the target directory, he may simply want to add a incremental count to each file, but we always ask for a new name :D , Instead let them decide how it goes

**Comment by laoneo** [comment]
I'm going to close this one. For further enhancements I'v opened a new issue #396 which should allow the user to rename the file when it already exists on upload. Thanks for all the work on this one as the outcome for now is very good!

**Comment by LynetteLo** [comment]
hello, could you teach me how to upload the same file name in the same time?

**Comment by laoneo** [comment]
You don't have to upload a file with the same name at the same time.
