### ISSUE TITLE
Fatel error in Media Manager

### ISSUE THREAD

**Issue by ciar4n** [joomla-projects/media-manager-improvement#23]
#### Steps to reproduce the issue
Navigate to Content -> Media

#### Expected result
Media Manager

#### Actual result
```
<div id="filesview">
<br>
<b>Fatal error</b>
: Call to undefined function finfo_open() in
<b>C:\xampp\htdocs\media-manager-improvement\administrator\components\com_media\models\file\adapter\local.php</b>
on line
<b>446</b>
<br>
</div>
```

#### System information (as much as possible)
PHP Version 5.6.11
mysqlnd 5.0.11

**Comment by dgt41** [comment]
@ciar4n did you follow the setup instructions: https://github.com/joomla-projects/media-manager-improvement/wiki

**Comment by jissereitsma** [comment]
@ciar4n @dgt41 I don't think this issue is due to a wrong setup. The PHP error mentions that a very basic PHP function `finfo_open()` is not existing in this environment. According to the official manual http://php.net/manual/en/function.finfo-open.php it is part of PHP, but also as a PECL. I am very surprised to see that this PHP module `fileinfo` is not included in your environment. Anyway, we can write this down as a compatibility issue. To be honest, I consider the `fileinfo` PHP module a basic module and if the hosting environment is missing this module, it is lacking in other modules as well - I would classify it as a non-mature environment. However, this single call would put additional minimum requirements on Joomla users, so we (I?) should work on removing this requirement. Let's keep this ticket open until that has been investigated.

**Comment by dgt41** [comment]
@jissereitsma I think @ciar4n want's to help with the UI part, if so it would be good idea to get him in the team.
@ciar4n already showcased his background with https://github.com/joomla/joomla-cms/pull/11832
So if he wants to help here my proposal is to get him aboard

**Comment by ciar4n** [comment]
@jissereitsma My PHP is sketchy at best but your comment was enough for me to resolve the issue. Thank you.

Thank you @dgt41 Would love to help where I can although. I had made a PR regarding the styling of the media manager ( #11874) and it was suggested I submit them here instead.

**Comment by jissereitsma** [comment]
Fixed in code now.
