### ISSUE TITLE
Deleting a file causes a crash

### ISSUE THREAD

**Issue by dgrammatiko** [joomla-projects/media-manager-improvement#231]
### Steps to reproduce the issue

Try to delete a file
An alert `respons 200` appears
Clicking ok forces the app to redirect to the dash board

### Expected result
File deleted, no more notifications

### Actual result
File deleted, but forcing redirect to dashboard

**Comment by kasvith** [comment]
@dgt41 I found the issue, it is because line 142 in api.json.php
We are not receiving a $data object for **delete** method, so in that case we can't use it for sendResponse as **$data** variable is not defined yet

XDebug result

<br />
<font size='1'><table class='xdebug-error xe-notice' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Undefined variable: data in /Applications/XAMPP/xamppfiles/htdocs/media-manager-improvement/administrator/components/com_media/controllers/api.json.php on line <i>142</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0086</td><td bgcolor='#eeeeec' align='right'>370880</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/Applications/XAMPP/xamppfiles/htdocs/media-manager-improvement/administrator/index.php' bgcolor='#eeeeec'>.../index.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0839</td><td bgcolor='#eeeeec' align='right'>378256</td><td bgcolor='#eeeeec'>require_once( <font color='#00bb00'>'/Applications/XAMPP/xamppfiles/htdocs/media-manager-improvement/administrator/includes/app.php'</font> )</td><td title='/Applications/XAMPP/xamppfiles/htdocs/media-manager-improvement/administrator/index.php' bgcolor='#eeeeec'>.../index.php<b>:</b>30</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.1509</td><td bgcolor='#eeeeec' align='right'>3239592</td><td bgcolor='#eeeeec'>Joomla\CMS\Application\CmsApplication->execute(  )</td><td title='/Applications/XAMPP/xamppfiles/htdocs/media-manager-improvement/administrator/includes/app.php' bgcolor='#eeeeec'>.../app.php<b>:</b>35</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.2353</td><td bgcolor='#eeeeec' align='right'>6471544</td><td bgcolor='#eeeeec'>Joomla\CMS\Application\AdministratorApplication->doExecute(  )</td><td title='/Applications/XAMPP/xamppfiles/htdocs/media-manager-improvement/libraries/src/CMS/Application/CMSApplication.php' bgcolor='#eeeeec'>.../CMSApplication.php<b>:</b>393</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>0.2441</td><td bgcolor='#eeeeec' align='right'>6889864</td><td bgcolor='#eeeeec'>Joomla\CMS\Application\AdministratorApplication->dispatch( ??? )</td><td title='/Applications/XAMPP/xamppfiles/htdocs/media-manager-improvement/libraries/src/CMS/Application/AdministratorApplication.php' bgcolor='#eeeeec'>.../AdministratorApplication.php<b>:</b>146</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>0.2509</td><td bgcolor='#eeeeec' align='right'>7051416</td><td bgcolor='#eeeeec'>Joomla\CMS\Component\ComponentHelper::renderComponent( ???, ??? )</td><td title='/Applications/XAMPP/xamppfiles/htdocs/media-manager-improvement/libraries/src/CMS/Application/AdministratorApplication.php' bgcolor='#eeeeec'>.../AdministratorApplication.php<b>:</b>103</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>7</td><td bgcolor='#eeeeec' align='center'>0.2527</td><td bgcolor='#eeeeec' align='right'>7057888</td><td bgcolor='#eeeeec'>Joomla\CMS\Component\ComponentHelper::executeComponent( ??? )</td><td title='/Applications/XAMPP/xamppfiles/htdocs/media-manager-improvement/libraries/src/CMS/Component/ComponentHelper.php' bgcolor='#eeeeec'>.../ComponentHelper.php<b>:</b>398</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>8</td><td bgcolor='#eeeeec' align='center'>0.2529</td><td bgcolor='#eeeeec' align='right'>7085032</td><td bgcolor='#eeeeec'>require_once( <font color='#00bb00'>'/Applications/XAMPP/xamppfiles/htdocs/media-manager-improvement/administrator/components/com_media/media.php'</font> )</td><td title='/Applications/XAMPP/xamppfiles/htdocs/media-manager-improvement/libraries/src/CMS/Component/ComponentHelper.php' bgcolor='#eeeeec'>.../ComponentHelper.php<b>:</b>424</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>9</td><td bgcolor='#eeeeec' align='center'>0.2573</td><td bgcolor='#eeeeec' align='right'>7385416</td><td bgcolor='#eeeeec'>Joomla\CMS\Controller\Controller->execute( ??? )</td><td title='/Applications/XAMPP/xamppfiles/htdocs/media-manager-improvement/administrator/components/com_media/media.php' bgcolor='#eeeeec'>.../media.php<b>:</b>30</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>10</td><td bgcolor='#eeeeec' align='center'>0.2573</td><td bgcolor='#eeeeec' align='right'>7385416</td><td bgcolor='#eeeeec'>MediaControllerApi->files(  )</td><td title='/Applications/XAMPP/xamppfiles/htdocs/media-manager-improvement/libraries/src/CMS/Controller/Controller.php' bgcolor='#eeeeec'>.../Controller.php<b>:</b>710</td></tr>
</table></font>
{"success":true,"message":null,"messages":null,"data":null}

**Comment by kasvith** [comment]
@laoneo can we close the issue as it was fixed?

**Comment by laoneo** [comment]
Yes

**Comment by dgrammatiko** [comment]
Thank you @kasvith
